# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72a88744cadf5965204e914b8c30a4a95fc98f9208cd4cf128029737ac8c6dda709404eabdd3253bdeba51b54de3c501d8399ae5912de91b85423d8bb5837b8a

test:
  secret_key_base: c419a4fff5ea30fdc0fa59c8147adb9d3e1db5ae1f89d8fe8157d61c4d20edacbcebfd3c80773af3e4dab897ef031ed4cfe1b80de6977b5c01c51bc1957a6818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
